### ISSUE TITLE
How to get cargo test results as JSON?

### ISSUE THREAD

**Issue by bcpeinhardt** [ctron/markdown-test-report#1]
Hey this looks fantastic and I'd love to use it but I can't seem to figure out how to get my cargo test results in JSON in the first place. I'd like to do 
```
fancy_command_to_run_cargo_test_with_json_output > test_results.json
markdown-test-report ./test_results.json -o test_results.md
```

**Comment by bcpeinhardt** [comment]
Well really I'd love to do what you have in the example, recorded test runs hosted as part of our CI/CD

**Comment by ctron** [comment]
You are right, that isn't clear at all. I amended the README, maybe you can take a look at let me know if that makes it clear: https://github.com/ctron/markdown-test-report#json-output-for-cargo-test

**Comment by bcpeinhardt** [comment]
Thanks! This helped a lot!
